#ifndef REFMON_KERNELVERS_LIMITS_H
#define REFMON_KERNELVERS_LIMITS_H

#define REFMON_KERNELVER_PROCMGT KERNEL_VERSION(5, 6, 0)
#define REFMON_KERNELVER_SFFS_OPS KERNEL_VERSION(6, 5, 0)
#define REFMON_KERNELVER_SYSCALLDEF KERNEL_VERSION(4, 17, 0)

#endif //REFMON_KERNELVERS_LIMITS_H
